services:
  db:
    image: postgres:16
    container_name: bookshelf_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: bookshelf_api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: bookshelf_frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata:
